### ISSUE TITLE
Error on get_pulse.py exec

### ISSUE THREAD

**Issue by imanbee** [thearn/webcam-pulse-detector#2]
Ubuntu 12.10 x64. Whan does it mean?

```
Traceback (most recent call last):
  File "get_pulse.py", line 125, in <module>
    App = getPulseApp()
  File "get_pulse.py", line 17, in __init__
    self.camera = Camera(camera=0) #first camera by default
  File "~/Downloads/webcam-pulse-detector-master/lib/device.py", line 10, in __init__
    self.shape = self.get_frame().shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by Chunix123** [comment]
I'm getting the same question on Windows 10. But as "maym86"'s say " Did you get errors in the install? It can still complete with errors in some modules. " I had double click to install "go-openmdao-0.13.0.py", so it's not okay.
It should install go-openmdao-0.13.0.py in cmd as a command " python  go-openmdao-0.13.0.py".
